services:
    - type: web
      name: salesforce-mini-backend
      runtime: node
      rootDir: backend
      buildCommand: npm install
      startCommand: npm start
      healthCheckPath: /api/health
      envVars:
          - key: NODE_VERSION
            value: 20
          - key: MONGODB_URI
            value: mongodb+srv://Reshika_salesforce_mini:Reshika%402003@cluster0.g2dtz78.mongodb.net/mini_salesforce?retryWrites=true&w=majority&appName=Cluster0
          - key: JWT_SECRET
            value: your_secret_key
          - key: JWT_EXPIRES_IN
            value: 1d
          - key: CLIENT_ORIGIN
            value: https://salesforce-mini-frontend.onrender.com
          - key: PORT
            value: 5000

    - type: web
      name: salesforce-mini-frontend
      runtime: static
      rootDir: frontend
      buildCommand: npm install && npm run build
      staticPublishPath: ./dist
      envVars:
          - key: NODE_VERSION
            value: 20
          - key: VITE_API_BASE_URL
            sync: false
      routes:
          - type: rewrite
            source: /*
            destination: /index.html
